#!/usr/bin/env bash
#
# multivac installer
#
# Installs multivac as a Claude Code skill and (if Codex is present) a Codex
# prompt, and drops a `multivac` launcher on your PATH so you can run it as a
# plain command. Re-running upgrades an existing install in place.
#
#   ./install.sh                 # install for the current user
#   ./install.sh --uninstall     # remove what this script installed
#
# Override locations with env vars (used mainly for testing):
#   CLAUDE_SKILLS_DIR  (default: ~/.claude/skills)
#   CODEX_PROMPTS_DIR  (default: ~/.codex/prompts)
#   MULTIVAC_BIN_DIR   (default: ~/.local/bin)
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
CLAUDE_SKILLS_DIR="${CLAUDE_SKILLS_DIR:-$HOME/.claude/skills}"
CODEX_PROMPTS_DIR="${CODEX_PROMPTS_DIR:-$HOME/.codex/prompts}"
MULTIVAC_BIN_DIR="${MULTIVAC_BIN_DIR:-$HOME/.local/bin}"
DEST="$CLAUDE_SKILLS_DIR/multivac"
LAUNCHER="$MULTIVAC_BIN_DIR/multivac"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

uninstall() {
  info "Removing launcher $LAUNCHER"; rm -f "$LAUNCHER"
  info "Removing skill $DEST";        rm -rf "$DEST"
  info "Removing Codex prompt $CODEX_PROMPTS_DIR/multivac.md"; rm -f "$CODEX_PROMPTS_DIR/multivac.md"
  bold "Uninstalled. (Your ~/.codex/AGENTS.md snippet, if you added one, was left untouched.)"
  exit 0
}

[ "${1:-}" = "--uninstall" ] && uninstall

# --- prerequisites --------------------------------------------------------
command -v python3 >/dev/null 2>&1 || die "python3 is required but not found on PATH."
info "Using $(python3 --version 2>&1)"

# --- bootstrap: fetch sources if run via `curl | bash` (no clone present) --
# When piped from the web, this script has no sibling files, so clone the repo
# into a cache dir and install from there. When run from a clone, use it as-is.
if [ ! -f "$REPO_DIR/bin/multivac.py" ]; then
  SRC="${MULTIVAC_SRC_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/multivac/src}"
  REPO_URL="${MULTIVAC_REPO_URL:-https://github.com/vrajdesai78/multivac.git}"
  REF="${MULTIVAC_REF:-main}"
  command -v git >/dev/null 2>&1 || die "git is required to bootstrap. Install git, or clone the repo and run ./install.sh."
  info "Fetching multivac ($REF) -> $SRC"
  if [ -d "$SRC/.git" ]; then
    git -C "$SRC" fetch --depth 1 origin "$REF" >/dev/null 2>&1
    git -C "$SRC" reset --hard FETCH_HEAD >/dev/null 2>&1
  else
    mkdir -p "$(dirname "$SRC")"
    git clone --depth 1 --branch "$REF" "$REPO_URL" "$SRC" >/dev/null 2>&1 \
      || die "failed to clone $REPO_URL (branch $REF)."
  fi
  REPO_DIR="$SRC"
fi

# --- install skill (Claude Code) ------------------------------------------
info "Installing skill -> $DEST"
mkdir -p "$DEST"
# Runtime files only (skip docs/, tests/, .git). Copy directory *contents* so
# re-running merges cleanly without nesting bin/bin.
for d in bin references codex; do
  mkdir -p "$DEST/$d"
  cp -R "$REPO_DIR/$d/." "$DEST/$d/"
done
for f in SKILL.md README.md LICENSE; do
  cp "$REPO_DIR/$f" "$DEST/$f"
done
# Don't ship Python bytecode caches.
find "$DEST" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
chmod +x "$DEST/bin/multivac.py"

# --- launcher on PATH -----------------------------------------------------
mkdir -p "$MULTIVAC_BIN_DIR"
case "$DEST" in
  *['"$`\']*) die "refusing to install: skill path contains unsafe characters: $DEST" ;;
esac
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# multivac launcher (generated by install.sh) -> $DEST
exec python3 "$DEST/bin/multivac.py" "\$@"
EOF
chmod +x "$LAUNCHER"
info "Launcher -> $LAUNCHER"
case ":$PATH:" in
  *":$MULTIVAC_BIN_DIR:"*) ;;
  *) warn "$MULTIVAC_BIN_DIR is not on your PATH. Add this to your shell profile:"
     printf '       export PATH="%s:$PATH"\n' "$MULTIVAC_BIN_DIR" >&2 ;;
esac

# --- Codex packaging (optional) -------------------------------------------
if command -v codex >/dev/null 2>&1; then
  mkdir -p "$CODEX_PROMPTS_DIR"
  cp "$REPO_DIR/codex/prompts/multivac.md" "$CODEX_PROMPTS_DIR/multivac.md"
  info "Codex prompt -> $CODEX_PROMPTS_DIR/multivac.md (invoke with /prompts:multivac)"
  info "To let Codex orchestrate the others, paste codex/AGENTS.snippet.md into ~/.codex/AGENTS.md"
fi

# --- readiness check ------------------------------------------------------
echo
info "Checking delegate CLIs (installed + which API-key env vars would be scrubbed):"
"$LAUNCHER" doctor || warn "doctor reported a problem — install/log in to any missing CLI."

echo
bold "multivac installed."
echo "Try:  multivac ask --tool codex --prompt 'explain this repo in one line' --mode plan"
echo "      multivac consensus --tools codex,grok,agy --prompt 'best way to do X?'"
echo "Docs: $DEST/README.md"
